slug: fdcsr
visit: nsrr_visit
charts:
- chart: study2
  title: Study Type
- chart: gender
  title: Gender
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://preview.sleepdata.org
